//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Home", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Customer.
        /// </summary>
        internal static string AddNewCustomer {
            get {
                return ResourceManager.GetString("AddNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new customer ?.
        /// </summary>
        internal static string AskToRegisterCustomer {
            get {
                return ResourceManager.GetString("AskToRegisterCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Created Successfully..
        /// </summary>
        internal static string ComplaintCreatedSuccessMsg {
            get {
                return ResourceManager.GetString("ComplaintCreatedSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Description.
        /// </summary>
        internal static string ComplaintDesc {
            get {
                return ResourceManager.GetString("ComplaintDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the description of the complaint or report.
        /// </summary>
        internal static string ComplaintDescPH {
            get {
                return ResourceManager.GetString("ComplaintDescPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complaint was not created, please try again later..
        /// </summary>
        internal static string ComplaintNotCreatedMsg {
            get {
                return ResourceManager.GetString("ComplaintNotCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no complaint with this number, check the complaint number and try again..
        /// </summary>
        internal static string ComplaintNotFound {
            get {
                return ResourceManager.GetString("ComplaintNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Number.
        /// </summary>
        internal static string ComplaintNumber {
            get {
                return ResourceManager.GetString("ComplaintNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Details.
        /// </summary>
        internal static string ComplaintSectionTitle {
            get {
                return ResourceManager.GetString("ComplaintSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Status.
        /// </summary>
        internal static string ComplaintStatus {
            get {
                return ResourceManager.GetString("ComplaintStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Business Center. All Rights Reserved 2025 ©.
        /// </summary>
        internal static string CopyrightSentence {
            get {
                return ResourceManager.GetString("CopyrightSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Complaint.
        /// </summary>
        internal static string CreateNewComplaint {
            get {
                return ResourceManager.GetString("CreateNewComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Customer.
        /// </summary>
        internal static string CreateNewCustomer {
            get {
                return ResourceManager.GetString("CreateNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client was not created, the ID number might already be registered. Please verify the data and try again..
        /// </summary>
        internal static string CustomerNotCreated {
            get {
                return ResourceManager.GetString("CustomerNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no customer found with such entered data..
        /// </summary>
        internal static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter customer info to search for and verifying the identity..
        /// </summary>
        internal static string CustomerSearchHelp {
            get {
                return ResourceManager.GetString("CustomerSearchHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        internal static string CustomerSectionTitle {
            get {
                return ResourceManager.GetString("CustomerSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A text message containing the verification code will be sent to your registered phone number ending with .
        /// </summary>
        internal static string FoundCustomerConfirmDesc {
            get {
                return ResourceManager.GetString("FoundCustomerConfirmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to verify your identity..
        /// </summary>
        internal static string FoundCustomerConfirmTitle {
            get {
                return ResourceManager.GetString("FoundCustomerConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Type.
        /// </summary>
        internal static string IdentityType {
            get {
                return ResourceManager.GetString("IdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi ID.
        /// </summary>
        internal static string IdentityTypeOne {
            get {
                return ResourceManager.GetString("IdentityTypeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        internal static string IdentityTypeThree {
            get {
                return ResourceManager.GetString("IdentityTypeThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident ID.
        /// </summary>
        internal static string IdentityTypeTwo {
            get {
                return ResourceManager.GetString("IdentityTypeTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number.
        /// </summary>
        internal static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquire About a Complaint.
        /// </summary>
        internal static string InquiryComplaint {
            get {
                return ResourceManager.GetString("InquiryComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Classification.
        /// </summary>
        internal static string MainClass {
            get {
                return ResourceManager.GetString("MainClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Main Classification.
        /// </summary>
        internal static string MainClassDefOption {
            get {
                return ResourceManager.GetString("MainClassDefOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Main Classification.
        /// </summary>
        internal static string MainClassPH {
            get {
                return ResourceManager.GetString("MainClassPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Reports in the SBC Complaints System.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t recieve verification code ?.
        /// </summary>
        internal static string OTPNotSent {
            get {
                return ResourceManager.GetString("OTPNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code is not sent, please try again later..
        /// </summary>
        internal static string OTPSendingError {
            get {
                return ResourceManager.GetString("OTPSendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number starting with 05 and followed by 8 digits..
        /// </summary>
        internal static string PhoneNumberValidationMsg {
            get {
                return ResourceManager.GetString("PhoneNumberValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent a confirmation sms code to your phone..
        /// </summary>
        internal static string PhoneOTPConfirmDesc {
            get {
                return ResourceManager.GetString("PhoneOTPConfirmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Verification.
        /// </summary>
        internal static string PhoneOTPConfirmTitle {
            get {
                return ResourceManager.GetString("PhoneOTPConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I certify that all the information provided is true and correct, and I agree to the terms and conditions, including the privacy policy and confidentiality agreement..
        /// </summary>
        internal static string RegistrationConfirmationHelp {
            get {
                return ResourceManager.GetString("RegistrationConfirmationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Code.
        /// </summary>
        internal static string ResendOTP {
            get {
                return ResourceManager.GetString("ResendOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Complaint.
        /// </summary>
        internal static string SearchComplaint {
            get {
                return ResourceManager.GetString("SearchComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Complaint Number.
        /// </summary>
        internal static string SearchComplaintPH {
            get {
                return ResourceManager.GetString("SearchComplaintPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Customer.
        /// </summary>
        internal static string SearchCustomer {
            get {
                return ResourceManager.GetString("SearchCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter customer info (ID Number or Phone Number or Email or Fullname).
        /// </summary>
        internal static string SearchCustomerPH {
            get {
                return ResourceManager.GetString("SearchCustomerPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Complaint.
        /// </summary>
        internal static string SendComplaint {
            get {
                return ResourceManager.GetString("SendComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something goes wrong, please try again later..
        /// </summary>
        internal static string SomethingGoesWrong {
            get {
                return ResourceManager.GetString("SomethingGoesWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string StatecodeActive {
            get {
                return ResourceManager.GetString("StatecodeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string StatecodeRejected {
            get {
                return ResourceManager.GetString("StatecodeRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved.
        /// </summary>
        internal static string StatecodeResolved {
            get {
                return ResourceManager.GetString("StatecodeResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Classification.
        /// </summary>
        internal static string SubClass {
            get {
                return ResourceManager.GetString("SubClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sub Classification.
        /// </summary>
        internal static string SubClassDefOption {
            get {
                return ResourceManager.GetString("SubClassDefOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Sub Classification.
        /// </summary>
        internal static string SubClassPH {
            get {
                return ResourceManager.GetString("SubClassPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer.
        /// </summary>
        internal static string SubmitNewCustomer {
            get {
                return ResourceManager.GetString("SubmitNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Verification Code.
        /// </summary>
        internal static string SubmitOTP {
            get {
                return ResourceManager.GetString("SubmitOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Complaints Survey.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
